### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by gtbluesky** [shishuo365/libcurl-android#1]
curl、openssl和zlib均使用github上所指向的版本
平台：Ubuntu 16.04 LTS
NDK：r13b
log：
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/gtbluesky/libcurl-android/jni/openssl/crypto'
../util/domd: 24: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
Makefile:136: recipe for target 'local_depend' failed
make[1]: *** [local_depend] Error 127
make[1]: Leaving directory '/home/gtbluesky/libcurl-android/jni/openssl/crypto'
Makefile:484: recipe for target 'depend' failed
make: *** [depend] Error 1
Error building openssl library
Error building curl library

**Comment by shishuo365** [comment]
@gtbluesky 之前的编译脚本只兼容了Mac系统，所以在linux系统上编译会报错，现在已经兼容，更新一下代码试试。

**Comment by gtbluesky** [comment]
@shishuo365 
换了Mac编译还是有问题：
平台：Mac 10.12.6
log：
making clean in tools...
rm -f *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
Error building openssl library
Error building curl library
------------------------------------------
单独编译curl也有问题：
checking for arm-linux-androideabi-gcc... /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/Users/xxx/libcurl-android/jni/curl':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error building curl library

**Comment by gtbluesky** [comment]
@shishuo365 

换了Mac编译还是有问题：
平台：Mac 10.12.6
log：
making clean in tools...
rm -f *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
Error building openssl library
Error building curl library
------------------------------------------
单独编译curl也有问题：
checking for arm-linux-androideabi-gcc... /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/Users/xxx/libcurl-android/jni/curl':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error building curl library

**Comment by gtbluesky** [comment]
@shishuo365 

换了Mac编译还是有问题：
平台：Mac 10.12.6
log：
making clean in tools...
rm -f *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
Error building openssl library
Error building curl library
------------------------------------------
单独编译curl也有问题：
checking for arm-linux-androideabi-gcc... /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/Users/xxx/libcurl-android/jni/curl':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error building curl library

**Comment by gtbluesky** [comment]
@shishuo365 
换了Mac编译还是有问题：
平台：Mac 10.12.6
log：
making clean in tools...
rm -f *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1
Error building openssl library
Error building curl library

单独编译curl也有问题：
checking for arm-linux-androideabi-gcc... /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/Users/xxx/libcurl-android/jni/curl':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error building curl library

**Comment by shishuo365** [comment]
@gtbluesky 从日志来看，Linux上编译的问题是依赖不全；Mac上编译的问题是NDK路径不对；
把你Mac系统上 jni/openssl/config.log 日志内容贴上来

**Comment by gtbluesky** [comment]
@shishuo365 
在Ubuntu上可以编译成功了，但前提必须使用ndk r13b，使用r17会编译出错

**Comment by shishuo365** [comment]
NDK随着版本升级，会调整API，依赖工具，ABI兼容，等内容，后续我会逐个检查一下高版本的兼容性问题。
