### ISSUE TITLE
Errors when try to build it against ndk-r20

### ISSUE THREAD

**Issue by LinArcX** [shishuo365/libcurl-android#5]
Hi. i want to build libcurl against __android-ndk-r20/__ and i get these errors:
```
make[1]: Leaving directory '/home/linarcx/Downloads/libcurl-android/jni/openssl/test'
making clean in tools...
make[1]: Entering directory '/home/linarcx/Downloads/libcurl-android/jni/openssl/tools'
rm -f *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff
make[1]: Leaving directory '/home/linarcx/Downloads/libcurl-android/jni/openssl/tools'
rm -f libcrypto.a libssl.a
rm -f openssl.pc libssl.pc libcrypto.pc
rm -f speed.* .pure
rm -f ../openssl-1.0.2p.tar
making depend in crypto...
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/linarcx/Downloads/libcurl-android/jni/openssl/crypto'
../util/domd: 24: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [Makefile:137: local_depend] Error 127
make[1]: Leaving directory '/home/linarcx/Downloads/libcurl-android/jni/openssl/crypto'
make: *** [Makefile:484: depend] Error 1
Error building openssl library
Error building curl library
```

**Comment by LinArcX** [comment]
Actually i made a [simple script](https://gist.github.com/LinArcX/1c8529946c6317da8153805dac519ac8) that only compile libCurl. 

But i get an error:
> checking whether the C compiler works... no
I'v noticed that in __ndk-r20__ this was removed:
`arm-linux-androideabi-gcc*`

These are all files in __ndk-r10e__:
> arm-linux-androideabi-addr2line*   arm-linux-androideabi-g++*         arm-linux-androideabi-gdb*         arm-linux-androideabi-objdump*   
arm-linux-androideabi-ar*          arm-linux-androideabi-gcc*         arm-linux-androideabi-gprof*       arm-linux-androideabi-ranlib*    
arm-linux-androideabi-as*          arm-linux-androideabi-gcc-4.9*     arm-linux-androideabi-ld*          arm-linux-androideabi-readelf*   
arm-linux-androideabi-c++*         arm-linux-androideabi-gcc-ar*      arm-linux-androideabi-ld.bfd*      arm-linux-androideabi-size*      
arm-linux-androideabi-c++filt*     arm-linux-androideabi-gcc-nm*      arm-linux-androideabi-ld.gold*     arm-linux-androideabi-strings*   
arm-linux-androideabi-cpp*         arm-linux-androideabi-gcc-ranlib*  arm-linux-androideabi-ld.mcld*     arm-linux-androideabi-strip*     
arm-linux-androideabi-dwp*         arm-linux-androideabi-gcov*        arm-linux-androideabi-nm*                                           
arm-linux-androideabi-elfedit*     arm-linux-androideabi-gcov-tool*   arm-linux-androideabi-objcopy*

And these files exists in __ndk-r20__:
>arm-linux-androideabi-addr2line*  arm-linux-androideabi-elfedit*    arm-linux-androideabi-nm*         arm-linux-androideabi-size*     
arm-linux-androideabi-ar*         arm-linux-androideabi-gprof*      arm-linux-androideabi-objcopy*    arm-linux-androideabi-strings*  
arm-linux-androideabi-as*         arm-linux-androideabi-ld*         arm-linux-androideabi-objdump*    arm-linux-androideabi-strip*    
arm-linux-androideabi-c++filt*    arm-linux-androideabi-ld.bfd*     arm-linux-androideabi-ranlib*                                     
arm-linux-androideabi-dwp*        arm-linux-androideabi-ld.gold*    arm-linux-androideabi-readelf*     

You can see that all *-gcc files removed from ndk in recent versions. What we can do?

**Comment by shishuo365** [comment]
请使用 android-ndk-r13 版本来编译项目，新版本移除了部分32位的支持，后续会考虑在不同的分支上升级NDK，以满足不同用户的需求。
注：android-ndk-r20支持的最低API=16，工具类APP可能会需要更低的API支持。
