### ISSUE TITLE
每次都是全量编译，因为缺少autoconf和automake等工具，编了好多回。。。

### ISSUE THREAD

**Issue by mulangren8** [shishuo365/libcurl-android#7]
编译需要autoconf,automake,libtoolize工具，建议提示先安装？

**Comment by shishuo365** [comment]
https://github.com/shishuo365/libcurl-android#before-build

Install dependent:

```
autoconf >= 2.57
automake >= 1.7
libtool  >= 1.4.2
GNU m4
nroff
perl
```

**Comment by ibaoger** [comment]
I will check these tools in build shell.
